// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: SequentialCommandGroup.

package frc.robot.commands;
import org.ejml.dense.block.MatrixOps_DDRB;

import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import frc.robot.Constants;
import frc.robot.subsystems.Conveyor;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.DriveTrain;
import frc.robot.subsystems.FeederSystemBack;
import frc.robot.subsystems.FeederSystemFront;
import frc.robot.subsystems.FrontIntakeArmSub;
import frc.robot.subsystems.Imu;
import frc.robot.subsystems.IntakeFront;
import frc.robot.subsystems.IntakeBack;
import frc.robot.subsystems.IntakeFrontArm;
import frc.robot.subsystems.ShooterDrive;
import frc.robot.subsystems.Sorter;
import frc.robot.subsystems.BeanBreakBack;
import frc.robot.subsystems.BeanBreakFront;
import frc.robot.subsystems.BeanBreakMid;


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class SequentialCommandGroup1 extends SequentialCommandGroup {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    public SequentialCommandGroup1(DriveTrain driveTrain, FrontIntakeArmSub frontarm, 
                                     ShooterDrive shoot, Sorter sort, IntakeFront intakeFront,
                                    Conveyor conveyor, FeederSystemFront feederfront, BeanBreakMid beanBreakMid,
                                    BeanBreakBack beanBreakBack, BeanBreakFront beanBreakFront  )
    {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    addCommands(
        // Add Commands here:
        // Also add parallel commands using the
        //
        // addCommands(
        //      new command1(argsN, subsystem),
        //      parallel(
        //          new command2(argsN, subsystem),
        //          new command3(argsN, subsystem)
        //      )    
     
        //  );
        //enabled intake suck in ball stop when ball is received
       // new IntakeFromFront(driveTrain,shoot,intakeFront,conveyor,
       // feederfront,sort,frontarm,beanBreakMid,beanBreakBack,beanBreakFront)

        //turn desired angle
       //new TurnAnglePID_IMU(driveTrain, 90)
     
      //drive desired distance
      new DriveDistance(driveTrain, 0.8, 15),
       new TurnAnglePID_IMU(driveTrain, 180),
       new DriveDistance(driveTrain, 0.8, 15)



       // new TurnAngleIMU(driveTrain, imu, 0.75,-90),
       // new TurnAngleIMU(driveTrain, imu, 0.75,90),
      //  new TurnAngleIMU(driveTrain, imu, 0.75,0)
        //new HeadingDrive(driveTrain, imu, 0.5, 5, 0)



        );
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
